### ISSUE TITLE
[Dev] Formatting + layout of use profile page

### ISSUE THREAD

**Issue by robodair** [sudouc/a117_mobile#11]
The profile page currently has a really basic layout.

Change this to include a profile image in a header box and more spaced out user details.

Include a section at the bottom where we might put "recent activity"

**Comment by Nintrex** [comment]
a profile image circle is now displayed in the top center of the window. An icon list now displays the name, email, and created date from the user, if these details are not found, it displays a place holder message.

recent activity was not done as @robodair  decided it was out of scope
