### ISSUE TITLE
[Dev] Format the details view for courses

### ISSUE THREAD

**Issue by kelvindem** [sudouc/a117_mobile#6]
Currently the course details page just dumps in the request body, change this so it's formatted nicely.

Hassle API about getting a route for course details

Details display should include:
Course Code:
Course Version:
Faculty:
Discipline(s):
UAC Code:
CRICOS Code:
ATAR:

**Comment by robodair** [comment]
This may also involve linking/navigating to units related to the course, if they are present in the response from the API

**Comment by ComputerGuruInTraining** [comment]
Working on it
